# Последняя версия docker-compose
version: '3'

# Создаем общую сеть deafult для всех контейнеров
networks:
  default:
    driver: bridge

# Создаем отдельные контейнеры
services:
  # Контейнер с веб-приложением
  app:
    # Собираем из Dockerfile
    build:
      # Корнем указываем корень основного проекта
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    # Показываем наружу 80 порт
    ports:
      - "${APP_EXT_PORT}:80"
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    # Запускаем только после db
    depends_on:
      - db
    # Линкуем внешнюю папку с исходниками внутрь
    volumes:
      - "../app:/var/www/app"
      - "../docker:/var/www/docker"
      - "../migrations:/var/www/migrations"
      - "./conf/nginx:/etc/nginx/sites-available"
  # Контейнер с базой данных
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    # Подключаем к общей сети с другими контейнерами
    networks:
      - default
    # Показываем наружу порт
    ports:
      - "${DB_EXT_PORT}:3306"
    # Задаем параметры для инициализации БД
    environment:
      # Пароль к БД
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      # Создаваемая по умолчанию бд
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    # Линкуем внешнюю папку для хранения БД
    volumes:
      - "./database:/var/lib/mysql"